### ISSUE TITLE
Is the any version support for php 7.3

### ISSUE THREAD

**Issue by lchhieu** [vienthuong/shopware-php-sdk#1]
I'm using laravel 8 and want to use this packpage. However, Laravel 8 only require php version from  ^7.3
So is there any version that supports from 7.3 or ^7.1 as well
Thx

**Comment by vienthuong** [comment]
Hi @lchhieu, 
Unfortunately, we used a lot of PHP 7.4 only features (typed properties, spread operators) so it can be too many works to support a lower PHP version. Please feel free to update the source in your fork to serve your needs.
And hey, we're about to release the Laravel SDK base on this SDK too, let us know if you're interested (sadly it also only support PHP 7.4 onward)
