### ISSUE TITLE
Error when trying to get Customers

### ISSUE THREAD

**Issue by olivero86** [vienthuong/shopware-php-sdk#10]
When I try to get Customers I get the following error:
Vin\ShopwareSdk\Data\Struct::addExtension(): Argument #2 ($extension) must be of type Vin\ShopwareSdk\Data\Struct, null given, called 
When I use other entities such as ProductDefinition, the code works fine.
Here is the code I used:
`

        $customerRepository = RepositoryFactory::create(CustomerDefinition::ENTITY_NAME);        
        $grantType = new ClientCredentialsGrantType(Configure::read('Shopware.ACCESS_KEY_ID'), Configure::read('Shopware.ACCESS_KEY_SECRET'));
        $adminClient = new AdminAuthenticator($grantType, Configure::read('Shopware.BASE_URL'));
        $accessToken = $adminClient->fetchAccessToken();

        $context = new Context(Configure::read('Shopware.BASE_URL'), $accessToken);        
        
        $criteria = new Criteria();
        $customers = $customerRepository->search($criteria, $context)->getEntities();
`

**Comment by vienthuong** [comment]
Hi @olivero86 can you suggest me which SHopware version you're using.
And thanks for reporting it, I will check it right away :)

**Comment by vienthuong** [comment]
Hi @olivero86 
I published a new release for bug fixed, can you update the latest version and verify if it works now?
https://github.com/vienthuong/shopware-php-sdk/releases/tag/1.3.1

**Comment by olivero86** [comment]
> Hi @olivero86
> I published a new release for bug fixed, can you update the latest version and verify if it works now?
> https://github.com/vienthuong/shopware-php-sdk/releases/tag/1.3.1

It's working without errors, thank you.
