### ISSUE TITLE
How to solve method not allowed issue when get token?

### ISSUE THREAD

**Issue by NGPrakash-Techshetra** [vienthuong/shopware-php-sdk#20]
I am getting error like this

```
[production.ERROR: {"errors":[{"code":"0","status":"405","title":"Method Not Allowed","detail":"No route found for \u0022GET https:\/\/shopware6.mystore.me\/api\/oauth\/token\u0022: Method Not Allowed (Allow: POST)"}]} {"exception":"[object] (Vin\\ShopwareSdk\\Exception\\AuthorizationFailedException(code: 405)](url)
```
```
[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 405): Client error: `POST http://shopware6.mystore.me/api/oauth/token` resulted in a `405 Method Not Allowed` response:
{\"errors\":[{\"code\":\"0\",\"status\":\"405\",\"title\":\"Method Not Allowed\",\"detail\":\"No route found for \\u0022GET https:\\/\\/shop (truncated...)
 at /var/www/tf/shared/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
```

Shopware store version: v6.4.6.1

It was working earlier. I don't know this error from shopware after getting upgraded 1.3.2 to 1.3.3 when composer updated.
How to solve this issue? Thanks

**Comment by vienthuong** [comment]
Hi @NGPrakash-Techshetra NG
I am checking it!

**Comment by vienthuong** [comment]
Seems I am not able to reproduce it 🤔 
Could you elaborate more detail in this thread or contact me directly (via Slack/Gmail) as levienthuong@gmail.com so we can  have a deeper look into it?
From your reporting, it seems your webserver proxied the POST http request to a GET https request so I guess it's might be an issue here

**Comment by NGPrakash-Techshetra** [comment]
Thanks for your reply.  I configured force SSL in nginx config. That's why I got this error. Its resolved now. Thanks for your support.
