### ISSUE TITLE
Configure Client

### ISSUE THREAD

**Issue by barbieswimcrew** [vienthuong/shopware-php-sdk#22]
Hi and thanks for that pretty SDK!

I've got a little question regarding the clients config. If I follow your example using a repository for searching the API there is no way to configure the client, is it? 

I have to configure `"verify" => false` in the client just like in the following example:

```
$this->client = new GuzzleClient(['defaults' => [
    'verify' => false
]]);
```
... but as far as I can see there is no way to do that when working with repositories. 

Could you let me know how to handle that? Thanks in advance 👍

**Comment by vienthuong** [comment]
Hi @barbieswimcrew, could you try to do this before calling repository methods?

```php
        $productRepository->createHttpClient(['defaults' => [
            'verify' => false
        ]]);
        $productRepository->setHttpClient($client);
```

**Comment by barbieswimcrew** [comment]
@vienthuong that did the trick! thanks for your help!
