### ISSUE TITLE
Media Handling

### ISSUE THREAD

**Issue by vienthuong** [vienthuong/shopware-php-sdk#23]
https://shopware.stoplight.io/docs/admin-api/ZG9jOjEyNjI1Mzkw-media-handling#upload-the-resource-directly

**Comment by qx54** [comment]
Is there any ETA for this?

**Comment by vienthuong** [comment]
@qx54 

Hey, currently no, I need some input for the requirements. Can you give me an idea of how you need this feature to be done? Then I can have a better idea of the feature

**Comment by t-poeschl** [comment]
Currently it isnt possible to handle Medias?

**Comment by vienthuong** [comment]
> o handle

@t-poeschl I mean you can still work with Media as other entities, just other specific apis for media is not available like upload file, etc. However, you can still use [AdminActionService](https://github.com/vienthuong/shopware-php-sdk/blob/master/src/Service/AdminActionService.php) for generic admin apis if you know the endpoint

**Comment by oliverkuehne** [comment]
for me, this works fine :)  here a very simple example:

`$id = Uuid::randomHex();
            $mediaRepo =  RepositoryFactory::create(MediaDefinition::ENTITY_NAME);

            $mediaRepo->create([
                'id' => $id,
                // 'mediaFolderId' => '<id>'
            ], $dest->shopware()->context());


            $adminService = new AdminActionService($dest->shopware()->context());
            $adminService->execute('post', "/api/_action/media/{$id}/upload?extension=jpg", [
                'url' => $url,
            ]);

            $adminService->execute('post', "/api/_action/media/{$id}/rename", [
                'fileName' => 'My Name '.time(),
            ]);`

**Comment by vienthuong** [comment]
I updated it in the lastest version, feel free to reopen ticket if you have any issue
And also I added a new MediaService, now you can use the MediaService instead
https://github.com/vienthuong/shopware-php-sdk/pull/44

**Comment by flagbird** [comment]
The link to the docs doesn't exist anymore and the context of this issue is gone. What was the reason to do a renaming of an newly uploaded file?

**Comment by vienthuong** [comment]
The API still exists (but somehow the docs are weirdly gone) so the use case could vary depending on the consumer

**Comment by flagbird** [comment]
@vienthuong Thanks for the answer. I don't see the need of doing a rename after an upload without a given context why. Someone copied and pasted this solution only with the link to this issue and I can't reverse-engineer the reason why it was done this way anymore.

**Comment by flagbird** [comment]
Hi @vienthuong, I think I left a wrong impression here. This is no issue with the lib itself. It's fine as it is, even in the older version. But someone in a project had to write code in a hurry that's based on @okuehne example and I tried to find out if `rename` right after `upload` was used for a reason, that was elaborated in the outdated docs link or if it was just copy-paste code to save time. I can't tell by reading the history of this issue. I've settled to drop the `rename`, update the `upload` logic for using a filename and see what will happen. Thanks again.

**Comment by vienthuong** [comment]
No worry @flagbird, I got your concern :) your assumption is correct, his example is just purely to showcase what you can possibly do with the media endpoints. If you have trouble with using the upload endpoint using endpoint please feel free to raise it as well
