### ISSUE TITLE
Criteria Limit Improvement

### ISSUE THREAD

**Issue by solverat** [vienthuong/shopware-php-sdk#25]
Currently, it is not possible to set criteria limit to `null`.

But this should be possible to allow lists without pagination:
https://github.com/shopware/platform/blob/7ed33d9f1ba28888eec93b3ff4f9ba141790a32e/src/Core/Framework/DataAbstractionLayer/Dbal/EntityReader.php#L369

Notice that you're no longer able to determinate this clause if `null` is an allowed value:
https://github.com/vienthuong/shopware-php-sdk/blob/91d0686a8ef22ba56b31fc7c572bdb161a960ce8/src/Data/Criteria.php#L310

***

**Bonus**: Currently, it is not possible to pass a custom `Criteria` instance to any `association` (It's possible to set dedicated limit rates to each association): 
https://github.com/vienthuong/shopware-php-sdk/blob/91d0686a8ef22ba56b31fc7c572bdb161a960ce8/src/Data/Criteria.php#L150

Maybe we should change `addAssociation(string $path)` to `addAssociation(string $path ?Criteria $criteria = null)` (which creates a new one if not passed to keep BC)?

**Comment by vienthuong** [comment]
@solverat thanks for your contribution 👍🏽 
For your second question
you can achieve it by

```php
$criteria->getAssociation('product')->addCriteria($criteria);
```

**Comment by solverat** [comment]
> @solverat thanks for your contribution 👍🏽 For your second question you can achieve it by
> 
> ```
> $criteria->getAssociation('product')->addCriteria($criteria);
> ```

ah, i see! Thanks!

**Comment by lutek** [comment]
with this got error 
```
$criteria->getAssociation('product')->addCriteria($criteria);
```
getAssociation returns criteria so should be:
```
$criteria->getAssociation('product')->setLimit(100);
```
could you add this to the readme or example? I spent some time to find this ;)
