### ISSUE TITLE
Malformed UTF-8

### ISSUE THREAD

**Issue by t-poeschl** [vienthuong/shopware-php-sdk#28]
Good Morning,

since an new Update of Shopware i get following error:

`{"errors":[{"code":"0","status":"500","title":"Internal Server Error","detail":"Malformed UTF-8 characters, possibly incorrectly encoded"}]}`

Maybe someone an idea?

**Comment by vienthuong** [comment]
Hi @t-poeschl can you show your request URL and payload so I can see if there're anywrong?

Maybe this commit is fixing it in the shopware core?
https://github.com/shopware/platform/commit/9b82ec295ba23492f5694c77245d1f5553416a37

**Comment by vienthuong** [comment]
Close due to inactivity
