### ISSUE TITLE
Delete relations via syncDeleted()

### ISSUE THREAD

**Issue by dag-inbase** [vienthuong/shopware-php-sdk#32]
Hi,

I am trying to delete relations between products and categories via syncDeleted(). I didn't find any working way to do it other than to change some code in your class and make a pull request today :)
You can find more information on this topic in the pull request itself.

Have a nice day!

Dag

**Comment by vienthuong** [comment]
I added a small comment :)

**Comment by dag-inbase** [comment]
Hi Vin Le,

thx for the quick reply!
I'll have a look into this tomorrow (it's already 12:45 a.m. CET here)

Greetings from Germany,
Dag
