### ISSUE TITLE
Wrong parameter type for the execute method in AdminActionService

### ISSUE THREAD

**Issue by jakub-groncki** [vienthuong/shopware-php-sdk#38]
In `Vin\ShopwareSdk\Service\AdminActionService` the `$data` parameter has type `array`:

```php
class AdminActionService extends ApiService
{
    public function execute(string $method, string $path, array $data = [], array $headers = []): ApiResponse
    {
        // ...
    }
        // ...
}
```

But this is wrong considering the fact that some endpoints consume [octet-streams](https://shopware.stoplight.io/docs/admin-api/b3A6MTMzMTcwNzM-upload-a-file-for-a-document).

This would need to be changed to array|string or just left as mixed by default, depending on the target PHP version.

**Comment by vienthuong** [comment]
Hi @jakub-groncki 
Thanks for pointing it out, I will update it soon

**Comment by vienthuong** [comment]
I updated it in the lastest version, feel free to reopen ticket if you have any issue
And also I added a new MediaService, now you can use the MediaService instead
https://github.com/vienthuong/shopware-php-sdk/pull/44
