### ISSUE TITLE
AdminActionService::execute should support upper case action string

### ISSUE THREAD

**Issue by mschop** [vienthuong/shopware-php-sdk#40]
Calling the AdminActionService's `action` method with `$method` = 'POST'  causes throwing `\InvalidArgumentException`

```
(new AdminActionService(...))->execute('POST', ...);
```

The allow list check should be made case insensitive.

Instead of:

```
if (!in_array($method, ['get', 'post', 'put', 'patch', 'delete'])) {
```

This:

```
if (!in_array(strtolower($method), ['get', 'post', 'put', 'patch', 'delete'])) {
```

**Comment by vienthuong** [comment]
I updated it in the lastest version, feel free to reopen ticket if you have any issue 
https://github.com/vienthuong/shopware-php-sdk/pull/44
