### ISSUE TITLE
Cant get Transaction and Delivery Status

### ISSUE THREAD

**Issue by tebeso** [vienthuong/shopware-php-sdk#42]
`
$repository = RepositoryFactory::create(StateMachineStateDefinition::ENTITY_NAME);

$criteria = new Criteria();

$criteria->addAssociations(['orderTransactions', 'orderDeliveries']);

$criteria->addFilter(new EqualsFilter('id', $orderId));
`

shouldnt that return the order state with the transaction and delivery status?

**Comment by vienthuong** [comment]
Thanks, I merged your PR
