### ISSUE TITLE
Don't cache entities

### ISSUE THREAD

**Issue by ckilb** [vienthuong/shopware-php-sdk#46]
Right now hydrated entities are cached in 
_\Vin\ShopwareSdk\Repository\Traits\EntityHydrator::hydrateEntity_

`$cacheKey = $entityRaw['type'] . '-' . $entityRaw['id'];`
`if (array_key_exists($cacheKey, $this->cache)) {`
`    return $this->cache[$cacheKey];`
`}`

This should imo get removed without replacement. 
I'd not expect the SDK to do caching for me. In case I want caching I could easily implement it on my own.

There are some downsides of caching:
- If you search for an entity without associations and later on search for the same entity with association, the "new" hydrated entity is actually the old one without the associations added -> this is what took me quite some time to figure out.

- If you use some web server that doesn't end the PHP progress after the request has been finished this value will be cached forever. Even if the next request comes in after minutes/days/weeks the old value of that entity is still cached. I know common webservers like Apache or Nginx with PHP-FPM start a new process with each request - but new approaches are coming and get more and more popular (Swoole, Roadrunner). 

Like I said I don't think caching is necessary (the request to actually get the entity data from Shopware is probably much slower than hydrating the entity) so I'd remove it. In case you think caching should still be present it would be nice to be able to enable/disable it (via Context flag?) or at least to clear it (via method call). 

===
Another proposal related:
For now I'd like to replace the method _hydrateEntity_ with my own. If _hydrateEntity_ would be public, _EntityHydrator_ would be a class that get's initialized by some factory and injected to the _EntityRepository_ this would be quite easy.
But as _hydrateEntity_ is a private trait method inside a Trait which is hardly coupled to _EntityRepository_ this is a bit tricky to do.
In general I'd suggest - at least for a library -  to avoid Traits and rely on DI instead.

===
PR: https://github.com/vienthuong/shopware-php-sdk/pull/47

**Comment by vienthuong** [comment]
I'd agree with your suggestion 👍🏽 
Thanks for your contribution :)

**Comment by ckilb** [comment]
hey @vienthuong  thanks for your feedback. just pushed the changelog 👍

**Comment by vienthuong** [comment]
Hi @ckilb ck
Can you resolve the conflict :) after that I can merge

**Comment by ckilb** [comment]
Hey @vienthuong 
thanks for merging! Could you tag the new version so Composer is able to find it? Thanks!
