### ISSUE TITLE
EntityRepository::searchIds does not throw ShopwareSearchResponseException

### ISSUE THREAD

**Issue by TobiasGraml11** [vienthuong/shopware-php-sdk#49]
I am implementing an exception handling regarding missing privileges.

During this, I noticed that `EntityRepository::search` does throw a `ShopwareSearchResponseException`, in case Guzzle returns a `BadResponseException`.
I would expect the same from `EntityRepository::searchIds`, as the exception could also occur there.

In my example the missing privilege was a manufacturer filter for the product.

![image](https://user-images.githubusercontent.com/51320851/188895139-f9b232fc-975d-46c3-84c1-69d36dbebf11.png)

![image](https://user-images.githubusercontent.com/51320851/188895397-7a4bb9b8-39fd-4a12-aa81-313995f42f14.png)

Cheers!

**Comment by vienthuong** [comment]
I will take care of it, thanks for reporting :)

**Comment by TobiasGraml11** [comment]
@vienthuong Thanks!
