### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by ChristopherDosin** [vienthuong/shopware-php-sdk#53]

**Comment by vienthuong** [comment]
Hi my friend @ChristopherDosin 
Could you describe more which part is not compatible with 8.1 :D Or you will make a PR?

**Comment by ChristopherDosin** [comment]
Hello my friend @vienthuong  :) 

Currently the packages requires PHP 8.0 -> 
https://github.com/vienthuong/shopware-php-sdk/blob/master/composer.json#L15

So this is basically blocking other packages that are requiring PHP 8.1

Not sure if we should just increase it to 8.1, or if we should update the whole code to PHP 8.1 and release a new version?

**Comment by vienthuong** [comment]
Ah sure, I think for "compatible" I think it's fine enough to add 8.* to the composer.json

**Comment by ChristopherDosin** [comment]
Perfect. Should i do a PR or do you want to do it? ^^

**Comment by vienthuong** [comment]
a PR is welcomed :D otherwise I will do it tomorrow or sth, and we should increase the package minor version :)

**Comment by vienthuong** [comment]
I just released PHP 8.1 compatibility in 1.7.0 version, feel free to reopen ticket if you met any issue with it :)
