### ISSUE TITLE
Call to a member function getSource() on null

### ISSUE THREAD

**Issue by nilesh-nitsan** [vienthuong/shopware-php-sdk#65]
PHP v7.4
Shopware v6.4

When I try to get a token using the below methods
  ```
$grantType = new ClientCredentialsGrantType($clientId, $clientSecret);
  $adminClient = new AdminAuthenticator($grantType, $shopUrl);
  $accessToken = $adminClient->fetchAccessToken();
```

I'm getting the issue Call to a member function getSource() on null.

![image](https://user-images.githubusercontent.com/59409022/220653382-e3efbca4-319c-4492-b193-c9bf2d3e9774.png)

I have also tried with a username and password as well. Still, the same issue will generate. Can you please let me know if anyone faced this issue or any solution for it?

Help is very appreciated.

Cheers, Nilesh

**Comment by vienthuong** [comment]
Hi @nilesh-nitsan 
Seems it's an error from Shopware app?
Could you list all your steps to reproduce it with an example code? And did you try it with PasswordGrantType?

**Comment by nilesh-nitsan** [comment]
Hi @vienthuong 
First of all, thank you for the quick answer. 

Actually, I have used this SDK in TYPO3 v10 CMS. Basically, I have tried Postman there is my app working well. It will return a response with the access token.

as mentioned above my code snippet, I have used the same way.  And yes I have also tried with the PasswordGrantType.

Is it possible this issue is caused by the Guzzle version?

Awaiting for your thoughts :) 

Thanks again!

**Comment by vienthuong** [comment]
Hi @nilesh-nitsan
Sorry for the late response, could you provide which exact shopware version and which sdk version you're using?

**Comment by nilesh-nitsan** [comment]
Hi @vienthuong 
I'm using Shopware version 6.4 and SDK version latest one.

**Comment by renickbuettner** [comment]
I just got the same error. Fixed it by removing the slash at the end of the api domain 🙈

**Comment by silverDuy** [comment]
Hi @nilesh-nitsan , @renickbuettner 
I created this https://github.com/vienthuong/shopware-php-sdk/pull/70 to fix this issue
