### ISSUE TITLE
Dieser Wert sollte nicht leer sein. c1051bb4-d103-4f74-8988-acbcafc7fdc3

### ISSUE THREAD

**Issue by soft-planet** [vienthuong/shopware-php-sdk#67]
Sehr geehrte Damen und Herren,

nach dem ich probiert habe mit der shopware-php-sdk eine Landingpage zu erstellen habe ich folgende Fehlermeldung bekommen:

`Next Vin\ShopwareSdk\Exception\ShopwareResponseException: {"errors":[{"code":"c1051bb4-d103-4f74-8988-acbcafc7fdc3","status":"400","detail":"Dieser Wert sollte nicht leer sein.","template":"This value should not be blank.","meta":{"parameters":{"{{ value }}":"null"}},"source":{"pointer":"\/0\/salesChannels"}}]} `

Welcher Wert sollte nicht leer sein?
Oder geht es um den Parameter value? oder den Parameter salesChannels?
Es wäre schön wenn der fehlende Parameter angegeben wird. 

mit freundlichem gruß
Chanel

**Comment by vienthuong** [comment]
Hi @soft-planet 
The error came from SW platform so we can't change the message. But from what I see, the salesChannels parameter is missing

Could you try to put this into your request payload? each sales channel is the one you need to assign your landing page to

[
    ....
    'salesChannels' => [
         [ 'id' => '<your sales channel 1 id>'],
         [ 'id' => '<your sales channel 2 id>'
    ],
]

**Comment by soft-planet** [comment]
Vielen dank hat geklappt!
