### ISSUE TITLE
Create Order Delivery

### ISSUE THREAD

**Issue by CnczubehoerEu** [vienthuong/shopware-php-sdk#73]
Hello together! I already use this library frequently to download orders and upload item information from SW6. Unfortunately, I do not manage to create deliveries in SW6. 

I have tinkered for me the simplest case: 

```
        $orderRepository = RepositoryFactory::create(OrderDeliveryDefinition::ENTITY_NAME);

        $data["orderId"] = $orderId;
        $data["stateId"] = "e2d3aa03f8684f53a9f02e5643580a23";

        $orderRepository->create($data, $this->authenticateSDK($order->getShop()));
```

This does not work. Am I on the right track? Ideally, does anyone have a working code example? Thanks a lot! Tobias

**Comment by SpiGAndromeda** [comment]
A lot of required data is missing for creating an order. You can find the required fields here: https://shopware.stoplight.io/docs/admin-api/914cd8f844e67-create-a-new-order-delivery-resources (keep in mind to unfold the "shippingCosts" field in the documentation as it is required as well).

Also keep in mind that SW6 creates an order delivery by itself it the order was placed via a storefront. SW can't handle multiple deliveries per order very well. The "overall" status over all deliveries is not handled correctly and the customer will often see a wrong status. So in most cases it makes more sense to update the existing order.

**Comment by vienthuong** [comment]
@CnczubehoerEu Feel free to reopen the issue with more error detail if the hint from @SpiGAndromeda does not work for your case :)
