### ISSUE TITLE
SDK version mismatch

### ISSUE THREAD

**Issue by flowl** [vienthuong/shopware-php-sdk#74]
README.md:

> You can use 1.x to connect to a sw 6.5 but for up-to-date schema and new 6.5 features, you should use 2.x version instead.

There is no version 2, no branch 2, no tag 2.
Most current tag is 1.7.3

**Comment by vienthuong** [comment]
Hi @flowl 
I released the 2.0.0 now, seems I forgot to create one after change the composer.json to 2.0.0 but now its fixed. Feel free to reopen if you have other issue with versioning
